# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """$env_var $all"""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The ➜ "success_symbol" segment is being set to "➜" with the color "bold green"

[username]
style_user = "white"
style_root = "white"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = " on [$hostname ](bold #F5BA78)"
disabled = false

[directory]
truncation_length = 1
truncation_symbol = "…/"
home_symbol = "󰋜 ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "󰈽"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󰆧 "
modified = " "
staged = '[++\($count\)](green)'
renamed = "󰑕 "
deleted = " "

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

